#' Import Excel Files to Global Environment
#'
#' @description
#' Reads a single sheet from an Excel file in a specified folder and assigns it
#' to the global environment with the name derived from the file name. The data is
#' converted to a data.table and column names are cleaned using janitor.
#'
#' @param folder A string specifying the name of the folder containing the Excel file.
#' @param file_name A string specifying the name of the Excel file to read, which will
#'   also become the variable name (lowercased, without .xlsx extension).
#' @param sheet A string specifying the name of the sheet to read.
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' import_excel_files_to_variables(
#'   folder = "data",
#'   file_name = "my_data.xlsx",
#'   sheet = "Sheet1"
#' )
#' # The data is now available as `my_data_source` in the global environment
#' }
#'
#' @export
import_excel_files_to_variables <- function(folder, file_name, sheet) {
    assign(
        x = paste0(
            stringr::str_to_lower(
                stringr::str_remove(file_name, ".xlsx")
            ),
            "_source"
        ),
        value = data.table::as.data.table(
            janitor::clean_names(
                openxlsx2::wb_to_df(
                    here::here(folder, file_name),
                    sheet = sheet
                )
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Import Microsoft Access Tables to Global Environment
#'
#' @description
#' Reads tables from a Microsoft Access Database and assigns them to the global
#' environment with the name specified by the table_name argument. The data is
#' converted to a data.table and column names are cleaned using janitor.
#'
#' @param connection A connection object to the Microsoft Access Database
#'   generated by `RODBC::odbcDriverConnect()`.
#' @param table_name A string specifying the name of the table to read, which will
#'   also become the variable name (lowercased).
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' # Create connection
#' conn <- RODBC::odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=path/to/db.accdb")
#'
#' # Import table
#' import_access_tables_to_variables(connection = conn, table_name = "MyTable")
#' # The data is now available as `mytable_source` in the global environment
#' }
#'
#' @export
import_access_tables_to_variables <- function(connection, table_name) {
    assign(
        x = paste0(stringr::str_to_lower(table_name), "_source"),
        value = data.table::as.data.table(
            janitor::clean_names(
                RODBC::sqlFetch(connection, table_name)
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Import SAS Files to Global Environment
#'
#' @description
#' Reads a single .sas7bdat SAS file in a specified folder and assigns it to the
#' global environment with the name derived from the file name. The data is
#' converted to a data.table and column names are cleaned using janitor.
#'
#' @param folder A string specifying the name of the folder containing the SAS file.
#' @param file_name A string specifying the name of the .sas7bdat SAS file to read,
#'   which will also become the variable name (lowercased, without .sas7bdat extension).
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' import_sas_files_to_variables(folder = "data", file_name = "my_data.sas7bdat")
#' # The data is now available as `my_data_source` in the global environment
#' }
#'
#' @export
import_sas_files_to_variables <- function(folder, file_name) {
    assign(
        x = paste0(
            stringr::str_to_lower(
                stringr::str_remove(file_name, ".sas7bdat")
            ),
            "_source"
        ),
        value = data.table::as.data.table(
            janitor::clean_names(
                haven::read_sas(
                    here::here(folder, file_name)
                )
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Import XPT Files to Global Environment
#'
#' @description
#' Reads a single .xpt file in a specified folder and assigns it to the global
#' environment with the name derived from the file name. The data is converted
#' to a data.table and column names are cleaned using janitor.
#'
#' @param folder A string specifying the name of the folder containing the .xpt file.
#' @param file_name A string specifying the name of the .xpt file to read,
#'   which will also become the variable name (lowercased, without .xpt extension).
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' import_xpt_files_to_variables(folder = "data", file_name = "my_data.xpt")
#' # The data is now available as `my_data_source` in the global environment
#' }
#'
#' @export
import_xpt_files_to_variables <- function(folder, file_name) {
    assign(
        x = paste0(
            stringr::str_to_lower(
                stringr::str_remove(file_name, ".xpt")
            ),
            "_source"
        ),
        value = data.table::as.data.table(
            janitor::clean_names(
                haven::read_xpt(
                    here::here(folder, file_name)
                )
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Import CSV Files to Global Environment
#'
#' @description
#' Reads a single .csv file in a specified folder and assigns it to the global
#' environment with the name derived from the file name. The data is read using
#' data.table::fread() and column names are cleaned using janitor.
#'
#' @param folder A string specifying the name of the folder containing the .csv file.
#' @param file_name A string specifying the name of the .csv file to read,
#'   which will also become the variable name (lowercased, without .csv extension).
#'
#' @return This function is called for its side effect of assigning the data.table
#'   to the global environment. Returns invisibly.
#'
#' @examples
#' \dontrun{
#' import_csv_files_to_variables(folder = "data", file_name = "my_data.csv")
#' # The data is now available as `my_data_source` in the global environment
#' }
#'
#' @export
import_csv_files_to_variables <- function(folder, file_name) {
    assign(
        x = paste0(
            stringr::str_to_lower(
                stringr::str_remove(file_name, ".csv")
            ),
            "_source"
        ),
        value = janitor::clean_names(
            data.table::fread(
                here::here(folder, file_name)
            )
        ),
        envir = .GlobalEnv
    )
    invisible()
}

#' Apply Column Name Mapping to a data.table
#'
#' @description
#' Renames columns in a data.table according to a central lookup CSV that maps
#' source-specific column names to predefined standard variable names. Only columns
#' listed in the mapping are renamed; all other columns pass through unchanged.
#' The data.table is modified by reference.
#'
#' @param dt A data.table whose columns should be renamed.
#' @param domain A string identifying the dataset domain (e.g., "ae", "dm", "lb").
#'   Used to filter the mapping file to the relevant rows.
#' @param map_path A string specifying the path to the column mapping CSV file,
#'   resolved relative to the project root via `here::here()`. The CSV must contain
#'   columns: `domain`, `source_col`, `standard_col`. Defaults to
#'   `"data/column_map.csv"`.
#'
#' @return The modified data.table (invisibly). The table is renamed in place by
#'   reference.
#'
#' @examples
#' \dontrun{
#' # After import: ae_source exists in .GlobalEnv
#' ae_clean <- data.table::copy(ae_source)
#' apply_column_map(ae_clean, domain = "ae")
#' # ae_clean now uses standard column names; ae_source is unchanged
#' }
#'
#' @export
apply_column_map <- function(dt, domain, map_path = "data/column_map.csv") {
    map_file <- here::here(map_path)
    if (!file.exists(map_file)) {
        warning("Column map file not found: ", map_file, ". No columns renamed.")
        return(invisible(dt))
    }

    col_map <- data.table::fread(map_file)
    col_map <- col_map[col_map$domain == domain, ]

    if (nrow(col_map) == 0L) {
        warning("No mappings found for domain '", domain, "' in ", map_path, ".")
        return(invisible(dt))
    }

    dt_names <- names(dt)
    matched <- col_map$source_col %in% dt_names
    if (any(!matched)) {
        missing_cols <- col_map$source_col[!matched]
        warning(
            "Column map references source columns not found in data: ",
            paste(missing_cols, collapse = ", ")
        )
    }

    col_map <- col_map[matched, ]
    if (nrow(col_map) > 0L) {
        data.table::setnames(dt, old = col_map$source_col, new = col_map$standard_col)
    }

    invisible(dt)
}

#' Export Data to Excel File
#'
#' @description
#' Exports a data.table or data.frame to an Excel file using writexl.
#' Automatically adds .xlsx extension and exports to "output-files" folder.
#'
#' @param data A data.table or data.frame to be exported.
#' @param file_name A string specifying the file name (without .xlsx extension).
#' @param output_folder A string specifying the output folder. Defaults to "output-files".
#' @param col_names Logical indicating whether to include column names. Defaults to TRUE.
#' @param format_headers Logical indicating whether to format headers. Defaults to TRUE.
#'
#' @return Invisibly returns the path to the saved file.
#'
#' @examples
#' \dontrun{
#' # Export a data.table to Excel
#' export_to_excel(mtcars, "car_data")
#' # Creates "output-files/car_data.xlsx"
#'
#' # Export to a different folder
#' export_to_excel(mtcars, "car_data", output_folder = "results")
#' }
#'
#' @export
export_to_excel <- function(data,
                            file_name,
                            output_folder = "output-files",
                            col_names = TRUE,
                            format_headers = TRUE) {
    file_path <- here::here(output_folder, paste0(file_name, ".xlsx"))

    writexl::write_xlsx(
        data,
        path = file_path,
        col_names = col_names,
        format_headers = format_headers
    )

    invisible(file_path)
}
